# Generated by Django 5.0.3 on 2024-03-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Cadastrar Usuários', 'verbose_name_plural': 'Cadastrar Usuários'},
        ),
    ]
