# Generated by Django 5.0.2 on 2024-02-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ano', models.DateField()),
                ('divisao_atual', models.CharField(max_length=1)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo_disputa', models.CharField(choices=[('ES', 'ESTADUAL'), ('NA', 'NACIONAL'), ('IN', 'INTERNACIONAL')], default='ES', max_length=50)),
                ('categoria', models.CharField(choices=[('CA', 'CAMPEONATO'), ('COPA', 'COPA')], default='CA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('posicao_principal', models.CharField(max_length=50)),
                ('numero_camisa', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('clube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sem_clube', to='core.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_conquista', models.DateField()),
                ('data_exata', models.DateField()),
                ('resultado', models.CharField(choices=[('CAMP', 'CAMPEÃO'), ('VICE', 'VICE-CAMPEÃO')], default='CAM', max_length=50)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clube')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competicao')),
            ],
        ),
    ]
