# Generated by Django 5.0.2 on 2024-02-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clube',
            old_name='ano',
            new_name='ano_fundacao',
        ),
    ]
