# Generated by Django 5.0.2 on 2024-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clube_divisao_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='divisao_atual',
            field=models.CharField(choices=[('A', 'Série A')], default='', max_length=50),
        ),
    ]
