# Generated by Django 5.0.2 on 2024-02-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_estado_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='clube',
        ),
        migrations.AddField(
            model_name='clube',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='clubee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sem_clube', to='core.clube'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
    ]
