# Generated by Django 5.0.2 on 2024-02-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_clube_uf_remove_jogador_clube_clube_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='clubee',
        ),
        migrations.AddField(
            model_name='jogador',
            name='clube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sem_clube', to='core.clube'),
        ),
    ]
