# Generated by Django 5.0.2 on 2024-02-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_jogador_clubee_jogador_clube'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
