# Generated by Django 5.0.2 on 2024-02-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jogador_cidade_jogador_estado_jogador_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='tipo_disputa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='clube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clube'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='competicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.competicao'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='resultado',
            field=models.CharField(max_length=100),
        ),
    ]
