# Generated by Django 5.0.2 on 2024-02-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_competicao_tipo_disputa_alter_titulo_clube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulo',
            name='ano_conquista',
        ),
    ]
