# Generated by Django 5.0.2 on 2024-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_titulo_ano_conquista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='ano_conquista',
            field=models.PositiveIntegerField(default=1900),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='data_exata',
            field=models.DateField(auto_now_add=True),
        ),
    ]
