# Generated by Django 5.0.2 on 2024-02-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_clube_ano_fundacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competicao',
            options={'verbose_name': 'Competição', 'verbose_name_plural': 'Competições'},
        ),
    ]
