# Generated by Django 5.0.2 on 2024-02-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_jogador_options_alter_pais_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
