# Generated by Django 5.0.2 on 2024-02-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_clube_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(null=True, upload_to='jogadores'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='escudo',
            field=models.ImageField(null=True, upload_to='clubes'),
        ),
    ]
