# Generated by Django 5.0.2 on 2024-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_jogador_foto_alter_clube_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='ano_fundacao',
            field=models.PositiveIntegerField(help_text='Ano que o Clube foi criado', verbose_name='Ano Fundação'),
        ),
    ]
