# Generated by Django 5.0.2 on 2024-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_clube_ano_fundacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='ano_fundacao',
            field=models.CharField(max_length=10),
        ),
    ]
