# Generated by Django 5.0.3 on 2024-04-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinos', '0002_item_treino_item_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default='N', max_length=1)),
                ('idade', models.IntegerField(default=0)),
                ('cpf', models.IntegerField(default=0)),
                ('telefone', models.IntegerField(default=0)),
                ('treino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treinos.treino')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('treinos', models.ManyToManyField(to='treinos.treino')),
            ],
        ),
    ]
