# Generated by Django 5.0.3 on 2024-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
