# Generated by Django 5.0.3 on 2024-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_aluno_cpf_alter_aluno_telefone'),
        ('treinos', '0002_item_treino_item_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='treinos',
            field=models.ManyToManyField(null=True, to='treinos.treino'),
        ),
    ]
